export const FETCH_USERS_START = "FETCH_USERS_START"; //iniciar
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"; //exito de la llamada api
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE"; //cuando falla la api

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

//create
export const CREATE_USERS_START = "CREATE_USERS_START";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";
export const CREATE_USERS_FAILURE = "CREATE_USERS_FAILURE";

//update
export const UPDATE_USERS_START = "UPDATE_USERS_START";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USERS_FAILURE = "UPDATE_USERS_FAILURE";
